name: Basic EC2 Provision with Terraform

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'EC2 Instance Name'
        required: true
        type: string
      instance_type:
        description: 'EC2 Instance Type'
        required: true
        default: 't2.micro'
        type: string
      aws_region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION}}
      TF_VAR_instance_name: ${{ github.event.inputs.instance_name }}
      TF_VAR_instance_type: ${{ github.event.inputs.instance_type }}
      TF_VAR_aws_region: ${{ github.event.inputs.aws_region }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve